<?php

namespace Database\Seeders;

use App\Models\Currency;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CurrenctSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('currencies')->insert([
            ['language_id' => 1,'uuid' =>Str::uuid(), 'code' =>'AFN' , 'name' => 'Afghani', 'symbol' => '؋', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'ALL' , 'name' => 'Lek', 'symbol' => 'Lek', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'ANG' , 'name' => 'Netherlands Antillian Guilder', 'symbol' => 'ƒ', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'ARS' , 'name' => 'Argentine Peso', 'symbol' => '$', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'AUD' , 'name' => 'Australian Dollar', 'symbol' => '$', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'AWG' , 'name' => 'Aruban Guilder', 'symbol' => 'ƒ', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'AZN' , 'name' => 'Azerbaijanian Manat', 'symbol' => 'ман', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'BAM' , 'name' => 'Convertible Marks', 'symbol' => 'KM', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' => 'BDT', 'name' => 'Bangladeshi Taka', 'symbol' => '৳', 'value' => 0, 'status' => 0],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'BBD' , 'name' => 'Barbados Dollar', 'symbol' => '$', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'BGN' , 'name' => 'Bulgarian Lev', 'symbol' => 'лв', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'BMD' , 'name' => 'Bermudian Dollar', 'symbol' => '$', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'BND' , 'name' => 'Brunei Dollar', 'symbol' => '$', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'BOB' , 'name' => 'BOV Boliviano Mvdol', 'symbol' => '$b', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'BRL' , 'name' => 'Brazilian Real', 'symbol' => 'R$', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'BSD' , 'name' => 'Bahamian Dollar', 'symbol' => '$', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'BWP' , 'name' => 'Pula', 'symbol' => 'P', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'BYR' , 'name' => 'Belarussian Ruble', 'symbol' => '₽', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'BZD' , 'name' => 'Belize Dollar', 'symbol' => 'BZ$', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'CAD' , 'name' => 'Canadian Dollar', 'symbol' => '$', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'CHF' , 'name' => 'Swiss Franc', 'symbol' => 'CHF', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'CLP' , 'name' => 'CLF Chilean Peso Unidades de fomento', 'symbol' => '$', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'CNY' , 'name' => 'Yuan Renminbi', 'symbol' => '¥', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'COP' , 'name' => 'COU Colombian Peso Unidad de Valor Real', 'symbol' => '$', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'CRC' , 'name' => 'Costa Rican Colon', 'symbol' => '₡', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'CUP' , 'name' => 'CUC Cuban Peso Peso Convertible', 'symbol' => '₱', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'CZK' , 'name' => 'Czech Koruna', 'symbol' => 'Kč', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'DKK' , 'name' => 'Danish Krone', 'symbol' => 'kr', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'DOP' , 'name' => 'Dominican Peso', 'symbol' => 'RD$', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'EGP' , 'name' => 'Egyptian Pound', 'symbol' => '£', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'EUR' , 'name' => 'Euro', 'symbol' => '€', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'FJD' , 'name' => 'Fiji Dollar', 'symbol' => '$', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'FKP' , 'name' => 'Falkland Islands Pound', 'symbol' => '£', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'GBP' , 'name' => 'Pound Sterling', 'symbol' => '£', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'GIP' , 'name' => 'Gibraltar Pound', 'symbol' => '£', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'GTQ' , 'name' => 'Quetzal', 'symbol' => 'Q', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'GYD' , 'name' => 'Guyana Dollar', 'symbol' => '$', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'HKD' , 'name' => 'Hong Kong Dollar', 'symbol' => '$', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'HNL' , 'name' => 'Lempira', 'symbol' => 'L', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'HRK' , 'name' => 'Croatian Kuna', 'symbol' => 'kn', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'HUF' , 'name' => 'Forint', 'symbol' => 'Ft', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'IDR' , 'name' => 'Rupiah', 'symbol' => 'Rp', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'ILS' , 'name' => 'New Israeli Sheqel', 'symbol' => '₪', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'IRR' , 'name' => 'Iranian Rial', 'symbol' => '﷼', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'ISK' , 'name' => 'Iceland Krona', 'symbol' => 'kr', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'JMD' , 'name' => 'Jamaican Dollar', 'symbol' => 'J$', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'JPY' , 'name' => 'Yen', 'symbol' => '¥', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'KGS' , 'name' => 'Som', 'symbol' => 'лв', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'KHR' , 'name' => 'Riel', 'symbol' => '៛', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'KPW' , 'name' => 'North Korean Won', 'symbol' => '₩', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'KRW' , 'name' => 'Won', 'symbol' => '₩', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'KYD' , 'name' => 'Cayman Islands Dollar', 'symbol' => '$', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'KZT' , 'name' => 'Tenge', 'symbol' => 'лв', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'LAK' , 'name' => 'Kip', 'symbol' => '₭', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'LBP' , 'name' => 'Lebanese Pound', 'symbol' => '£', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'LKR' , 'name' => 'Sri Lanka Rupee', 'symbol' => '₨', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'LRD' , 'name' => 'Liberian Dollar', 'symbol' => '$', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'LTL' , 'name' => 'Lithuanian Litas', 'symbol' => 'Lt', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'LVL' , 'name' => 'Latvian Lats', 'symbol' => 'Ls', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'MKD' , 'name' => 'Denar', 'symbol' => 'ден', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'MNT' , 'name' => 'Tugrik', 'symbol' => '₮', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'MUR' , 'name' => 'Mauritius Rupee', 'symbol' => '₨', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'MXN' , 'name' => 'MXV Mexican Peso Mexican Unidad de Inversion (UDI]', 'symbol' => '$', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'MYR' , 'name' => 'Malaysian Ringgit', 'symbol' => 'RM', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'MZN' , 'name' => 'Metical', 'symbol' => 'MT', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'NGN' , 'name' => 'Naira', 'symbol' => '₦', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'NIO' , 'name' => 'Cordoba Oro', 'symbol' => 'C$', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'NOK' , 'name' => 'Norwegian Krone', 'symbol' => 'kr', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'NPR' , 'name' => 'Nepalese Rupee', 'symbol' => '₨', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'NZD' , 'name' => 'New Zealand Dollar', 'symbol' => '$', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'OMR' , 'name' => 'Rial Omani', 'symbol' => '﷼', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'PAB' , 'name' => 'USD Balboa US Dollar', 'symbol' => 'B/.', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'PEN' , 'name' => 'Nuevo Sol', 'symbol' => 'S/.', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'PHP' , 'name' => 'Philippine Peso', 'symbol' => 'Php', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'PKR' , 'name' => 'Pakistan Rupee', 'symbol' => '₨', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'PLN' , 'name' => 'Zloty', 'symbol' => 'zł', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'PYG' , 'name' => 'Guarani', 'symbol' => 'Gs', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'QAR' , 'name' => 'Qatari Rial', 'symbol' => '﷼', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'RON' , 'name' => 'New Leu', 'symbol' => 'lei', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'RSD' , 'name' => 'Serbian Dinar', 'symbol' => 'Дин.', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'RUB' , 'name' => 'Russian Ruble', 'symbol' => 'руб', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'SAR' , 'name' => 'Saudi Riyal', 'symbol' => '﷼', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'SBD' , 'name' => 'Solomon Islands Dollar', 'symbol' => '$', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'SCR' , 'name' => 'Seychelles Rupee', 'symbol' => '₨', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'SEK' , 'name' => 'Swedish Krona', 'symbol' => 'kr', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'SGD' , 'name' => 'Singapore Dollar', 'symbol' => '$', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'SHP' , 'name' => 'Saint Helena Pound', 'symbol' => '£', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'SOS' , 'name' => 'Somali Shilling', 'symbol' => 'S', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'SRD' , 'name' => 'Surinam Dollar', 'symbol' => '$', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'SVC' , 'name' => 'USD El Salvador Colon US Dollar', 'symbol' => '$', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'SYP' , 'name' => 'Syrian Pound', 'symbol' => '£', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'THB' , 'name' => 'Baht', 'symbol' => '฿', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'TRY' , 'name' => 'Turkish Lira', 'symbol' => 'TL', 'value' => 0, 'status' => 1 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'TTD' , 'name' => 'Trinidad and Tobago Dollar', 'symbol' => 'TT$', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'TWD' , 'name' => 'New Taiwan Dollar', 'symbol' => 'NT$', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'UAH' , 'name' => 'Hryvnia', 'symbol' => '₴', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'USD' , 'name' => 'US Dollar', 'symbol' => '$', 'value' => 0, 'status' => 1 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'UYU' , 'name' => 'UYI Uruguay Peso en Unidades Indexadas', 'symbol' => '$U', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'UZS' , 'name' => 'Uzbekistan Sum', 'symbol' => 'лв', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'VEF' , 'name' => 'Bolivar Fuerte', 'symbol' => 'Bs', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'VND' , 'name' => 'Dong', 'symbol' => '₫', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'XCD' , 'name' => 'East Caribbean Dollar', 'symbol' => '$', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'YER' , 'name' => 'Yemeni Rial', 'symbol' => '﷼', 'value' => 0, 'status' => 0 ],
            ['language_id' => 1,'uuid' =>Str::uuid(),'code' =>'ZAR' , 'name' => 'Rand', 'symbol' => 'R', 'value' => 0, 'status' => 0 ]
        ]);
    }
}
